# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: aaa0a81e104c9713253900867087be216c610d720ed418a5aa54f3e8468ba5274dc8cf83af882e2534f39af406cd8c1d425606915013c8d21645ccb6d396b99d

test:
  secret_key_base: 6353db3953bdbe82cda44ce13bcbecee4414bba517e75b52584a7a3bbb25f1708dfbf7f543a663c5bdc0f7256adb3909ebf0215c3243b01cc17cd2b1955bf586

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: f155550327a2a02367328e3e0e0298ebe8675064350f829ad808827dab0023002dc7588df20d8eb8a6ba554f5127270437f346aa0f6c86e54a1b902ece3465b5
